export const songs = [
  {
    id: 1,
    title: 'Вальсок',
    year: 2025,
    genre: 'Вальс',
    language: 'Русский',
    story: 'Юноша приглашает девушку. Время останавливается. Музыка начинается.',
    views: 70000,
    featured: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=o4n4XqqRCbg&list=RDo4n4XqqRCbg&start_radio=1',
  },
  {
    id: 2,
    title: 'Мы встретимся',
    year: 2025,
    genre: 'Лирическая песня о судьбе',
    language: 'Русский',
    story: 'Первое слово, с которого всё началось.',
    views: 12000,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=ewS-B7VMGTU&list=RDewS-B7VMGTU&start_radio=1',
  },
  {
    id: 3,
    title: 'Тараторка',
    year: 2025,
    genre: 'Весёлый шансон',
    language: 'Русский',
    story: 'Когда слова на одном языке не вмещают всего.',
    views: 8500,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=atMqPGupv9I&list=RDatMqPGupv9I&start_radio=1',
  },
  {
    id: 4,
    title: 'Разворошен очаг',
    year: 2025,
    genre: 'Лирический шансон о любви',
    language: 'Русский',
    story: 'Лирическая песня о любви, памяти и внутреннем огне, который не гаснет, даже когда прошлое уже невозможно вернуть. Это искренний мужской рассказ, наполненный теплом, болью и достоинством прожитых чувств.',
    views: 14200,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=DsKxcyMo15c&list=RDDsKxcyMo15c&start_radio=1',
  },
  {
    id: 5,
    title: 'Сапожки',
    year: 2025,
    genre: 'Лирический шансон',
    language: 'Русский',
    story: 'Лирическая авторская песня в жанре шансона о любви, заботе и тихом человеческом тепле. Это история, рассказанная просто и искренне — о чувствах, которые живут в деталях, в памяти и в сердце.',
    views: 6300,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=zuHlnM2yhq0&list=RDzuHlnM2yhq0&start_radio=1',
  },
  {
    id: 6,
    title: 'Осенний сад',
    year: 2025,
    genre: 'Песня о чувствах и времени',
    language: 'Русский',
    story: 'Это лирическая песня о времени, когда чувства становятся тише, но глубже и честнее. Это история о любви, которая не кричит, а живёт в паузах, взглядах и осенней тишине.',
    views: 9800,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=QRKqRM2rCNM&list=RDQRKqRM2rCNM&start_radio=1',
  },
  {
    id: 7,
    title: 'Наше танго',
    year: 2025,
    genre: 'Romantic Tango Song',
    language: 'Русский',
    story: 'Время. На любом языке оно уходит одинаково.',
    views: 11200,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=YG6Xgp2X0ic&list=RDYG6Xgp2X0ic&start_radio=1',
  },
  {
    id: 8,
    title: 'Звездопад',
    year: 2025,
    genre: 'Романтическая баллада о любви и вечности',
    language: 'Русский',
    story: 'Это признание в любви, обращённое к звёздам и к женщине, чьё присутствие делает мир ярче даже в темноте. Это история о мгновениях, когда небо и сердце сливаются воедино, о счастье, которое падает с небес, как звёздный дождь.',
    views: 7600,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=_ybScsv74Ls&list=RD_ybScsv74Ls&start_radio=1',
  },
  {
    id: 9,
    title: 'Девочка, девочка',
    year: 2025,
    genre: 'Быстрый танцевальный хит',
    language: 'Русский',
    story: 'Не одиночество как беда. Одиночество как состояние.',
    views: 19400,
    featured: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=irORc22mvUw&list=RDirORc22mvUw&start_radio=1',
  },
  {
    id: 10,
    title: 'Shana Tova u-Metuka',
    year: 2025,
    genre: 'Rosh Hashanah Song',
    language: 'Русский',
    story: 'Эта песня посвящена еврейскому Новому году — Рош ха-Шана — дню, когда мы зажигаем свечи, собираемся с близкими, желаем добра, здоровья и мира друг другу и всему миру.',
    views: 22100,
    featured: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=D6T-rWbyzoo',
  },
  {
    id: 11,
    title: 'Облака',
    year: 2025,
    genre: 'Душевная баллада',
    language: 'Русский',
    story: 'У каждого своя дорога. Но иногда они пересекаются.',
    views: 16700,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=NSIR0PTudoE',
  },
  {
    id: 12,
    title: 'Храни тебя Господь',
    year: 2025,
    genre: 'Музыка',
    language: 'Русский',
    story: 'Это песня-молитва, наполненная светом и теплом. Она о том, как мы просим защиты для самых близких людей: в дороге и в тишине, в толпе и в одиночестве, в любви и в разлуке.',
    views: 13500,
    featured: false,
    youtubeUrl: 'https://www.youtube.com/watch?v=DnXPrGD-YxM',
  },
]

export const stories = [
  {
    id: 1,
    title: 'Вальсок',
    subtitle: 'История одной песни, которую услышали 70 000 раз',
    image: null,
    imageAlt: 'Тёплый концертный зал, золотистый свет',
    mood: 'warm',
    excerpt: 'Август 2025 года. Вечер. Я сидела на кухне. Рука потянулась к листку бумаги и я написала «Замерло всё вокруг...»',
    linkedSong: 'Вальсок',
  },
  {
    id: 2,
    title: 'Одна из моих историй',
    subtitle: '',
    image: null,
    imageAlt: 'Ночная дорога, фонарь, силуэт',
    mood: 'dark',
    excerpt: 'Иногда человек может быть рядом с тобой всего два дня, а потом отсутствовать тридцать лет — и всё равно остаться самым главным человеком твоей жизни.',
    linkedSong: 'Февраль',
  },
  {
    id: 3,
    title: 'Как из ожидания родилась надежда',
    subtitle: '',
    image: null,
    imageAlt: 'Лист бумаги с рукописью, рядом чашка кофе',
    mood: 'night',
    excerpt: 'Она ещё не пришла. Но он уже знал — они встретятся.',
    linkedSong: 'Мы встретимся',
  },
]

export const languages = [
  { code: 'ru', label: 'Русский', dir: 'ltr' },
  { code: 'en', label: 'English', dir: 'ltr' },
  { code: 'de', label: 'Deutsch', dir: 'ltr' },
  { code: 'it', label: 'Italiano', dir: 'ltr' },
  { code: 'fr', label: 'Français', dir: 'ltr' },
  { code: 'ar', label: 'العربية', dir: 'rtl' },
  { code: 'he', label: 'עברית', dir: 'rtl' },
]

export const wordStream = [
  'любовь', 'память', 'война', 'одиночество', 'радость',
  'потеря', 'надежда', 'жизнь', 'дорога', 'тишина',
  'свет', 'ночь', 'встреча', 'разлука', 'время',
  'голос', 'слово', 'сердце', 'небо', 'дом',
]

export const songTitlesCloud = [
  'Вальсок', 'Привет', 'Одиночество', 'Надежда', 'Дорога',
  'Память', 'Bella', 'Dear Memory', 'Abends', 'La Strada',
  'Тишина', 'Встреча', 'Голос', 'Свет', 'Ночь',
  'Зиккарон', 'Вакт', 'Tempo', 'Lumière', 'Stille',
  'Любовь', 'Жизнь', 'Сердце', 'Небо', 'Дом',
  'История', 'Слово', 'Нота', 'Пауза', 'Финал',
]
